version: "3"
services:
  ms:
    container_name: hr-api-gateway-zuul
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8765:8765"
    command: "-P"
networks:
  default:
    external:
      name: hr-payroll-net