version: "3"
services:
  ms:
    container_name: hr-config-server
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8888:8888"
    environment:
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_PASS=${GITHUB_PASS}
networks:
  default:
    external:
      name: hr-payroll-net