version: "3"
services:
  hr-eureka-server:
    container_name: hr-eureka-server
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8761:8761"
networks:
  default:
    external:
      name: hr-payroll-net